// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"net/http"

	"InvertedCow/config"
	"InvertedCow/controller"
	"InvertedCow/dao"
	"InvertedCow/data"
	"InvertedCow/router"
	"InvertedCow/service"
)

// Injectors from wire.go:

func initApp(appConfig *config.AppConfig) (*http.Server, error) {
	db := data.NewGormClient(appConfig)
	client := data.NewRedisClient(appConfig)
	cos := data.NewCos(appConfig)
	userDao := dao.NewUserDao()
	accountService := service.NewAccountService(appConfig, db, client, cos, userDao)
	accountController := controller.NewAccountController(accountService)
	postDao := dao.NewPostDao()
	sourceDao := dao.NewSourceDao()
	postService := service.NewPostService(appConfig, db, cos, client, postDao, sourceDao)
	postController := controller.NewPostController(postService)
	controllerController := controller.NewController(accountController, postController)
	engine := router.SetupRouter(controllerController)
	server := newApp(engine, appConfig)
	return server, nil
}
